### ISSUE TITLE
Не хватает схем для интерфейса

### ISSUE THREAD

**Issue by Lofetty** [SaPeUlDi/TestGameNazvanieVremennoe#1]
<b>В главном меню:</b>
<ol>
  <li>Настройка
  <li>Ачивки
  <li>Разработчики
  <li>Загрузка игры
</ol>
<b>В меню паузы:</b>
<ol>
  <li>Настройки
  <li>Сохранение игры
  <li>Загрузка игры
</ol>

P.S. Файл "Эскизы к ТЗ.vsd" для Visio 2003

**Comment by deadmoroz583** [comment]
[Схемы.zip](https://github.com/SaPeUlDi/TestGameNazvanieVremennoe/files/2463929/default.zip)
